### ISSUE TITLE
Checksum calculation for ISBN-10 is wrong

### ISSUE THREAD

**Issue by thinkmobilede** [biblys/php-isbn-class#1]
Thanks for the great work. 

I found that the checksum calculation for ISBN-10 seems to be wrong. Line 285 should be 
$sum = (($c[0] * 1) + ($c[1] * 2) + ($c[2] * 3) + ($c[3] * 4) + ($c[4] * 5) + ($c[5] * 6) + ($c[6] * 7) + ($c[7] * 8) + ($c[8] * 9)) % 11;

Best regards,
Christian

**Comment by iwazaru** [comment]
Well not according to what I understand of : https://en.wikipedia.org/wiki/International_Standard_Book_Number#ISBN-10_check_digit_calculation

Do you have an ISBN example for which the checksum calculation fails ?

**Comment by thinkmobilede** [comment]
The ISBN 3464603520 gives 11 as checksum. I checked your link. It is iinteresting that de.wikipedia.org and en.wikipedia.org have different calculations. Based on the English version you are missing one module and the calculation hast to be 

$sum = (11 - (($c[0] * 10) + ($c[1] * 9) + ($c[2] * 8) + ($c[3] * 7) + ($c[4] * 6) + ($c[5] * 5) + ($c[6] * 4) + ($c[7] * 3) + ($c[8] * 2)) % 11) % 11;

**Comment by iwazaru** [comment]
Thanks for the additional info! I fixed it and added some tests so it won't happen again.
